name: Code Review AI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
        pr:
          description: "PR number"
          required: true

permissions:
  pull-requests: write
  contents: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff FETCH_HEAD --unified=3 > diff.patch

      - name: Call review API
        id: review
        run: |
          DIFF=$(cat diff.patch | jq -Rs .)
          RESPONSE=$(curl -s -X POST http://w8gw848s04ssgk8sowc4www4.91.98.166.129.sslip.io/review/webhook \
            -H "Content-Type: application/json" \
            -d "{\"diff\":$DIFF}")
          {
            echo "result<<EOF"
            echo "$RESPONSE"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Post result to PR
        if: ${{ github.event.pull_request.number || github.event.inputs.pr }} # ensures the step only runs on PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -F body=- << 'EOF'
          ${{ steps.review.outputs.result }}
          EOF
